### PR TITLE
Fix casein select form helper not passing html options to form select helper

### LINKED ISSUE #6: Cannot create form with multiple select option
Hello, 

I'm testing out Casein for a project, and we are looking to create a has_many relationship (in our current custom form, we are using nested attributes). 

I created a casein_select form that looks like this: 
<%= casein_select f, f.object, :photos, Photo.all, {multiple: true} %>

However, it looks like the options hash isn't being respect. 

Any suggestions for this issue, and for representing has_many polymorphic relationships in general? 

Thanks for the help!

### PR DESCRIPTION
**Pull request by guzart**
Allows the casein select helper options to pass through to the form select helper.

Fixes #6

### CODE REVIEW

**Comment by abeltje1** [comment]
Why isn't this merged in yet?

**Comment by brchristian** [comment]
@guzart I’m fairly new as a casein admin and still familiarizing myself with some of this code. Can you give me some context here? What’s an example of a behavior that doesn’t work in the current `master` that works once we merge this PR? Thanks!

**Comment by abeltje1** [comment]
Welcome dear new admin! The problem is that select, just as collection_select does not render all options passed to the options hash. I've tried adding multiple: true to both, but it didn't work. The problem seems to be that the methods for select and collection_select do not apply HTML options to the created HTML elements, hence why multiple: true doesn't work. I'm not 100% sure this solves it, but it seems like the right approach.

**Comment by abeltje1** [comment]
It does render 'normal' options though! that's why the example: 
`casein_collection_select f, f.object, :article, :author_id, Author.all, :id, :name, { prompt: 'Select author' }` actually does work

**Comment by guzart** [comment]
It's been a while, but I believe the problem trying to solve was precisely passing `multiple: true` option to the `select`, in order to have a multiple select box, so Reference #6

**Comment by guzart** [comment]
as @abeltje1  mentions, the problem is when passing [`html_options`](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-select) to the `select` helper.

**Comment by brchristian** [comment]
I think I see what you’re saying. Sorry to be dense, but can you offer me an example of a line that fails in the current `master` and works if this PR is merged? Otherwise I’m going to have a hard time being sure this is working as intended.

**Comment by abeltje1** [comment]
casein_collection_select f, f.object, :article, :author_id, Author.all, :id, :name, { multiple: 'true'}

**Comment by abeltje1** [comment]
even though this PR is made for casein_select instead of casein_collection_select, exactly the same logic applies to both methods, hence my example.

**Comment by russellquinn** [comment]
Hey everyone, I just spent some time looking into this. It's true that it's not possible to pass `multiple` through. Or, more specifically, Casein only allows a `class` value to be passed through to the underlying `select`'s `html_options` parameter.  So, yeah, the problem is real. Thanks for spotting it!

I don't think the proposed fix is without problems though. Firstly, it needs `strip_casein_options` to be applied to it. Secondly, any html options are also going to be passed through to `select`'s `options` parameter. Thirdly, any solution should be applied to all the other Casein form helpers that suffer from the same problem. Finally, it needs to be backwards compatible with existing code.

I wonder if the best approach would be adding a separate `html_options` optional param to all the Casein form helpers that need it? (i.e. all the ones that currently only allow `class` to be passed through via the `merged_class_hash` method). But then to provide backwards compatibility we'd still need to pass through `class` from the standard `options` hash. Phew!

So, maybe something like this?

```
def casein_select form, obj, attribute, option_tags, options = {}, html_options = {}

     html_options_to_use = merged_class_hash(options, 'form-control') #legacy support
     html_options_to_use = options_hash_with_merged_classes(html_options, html_options_to_use[:class])
      
     casein_form_tag_wrapper(form.select(attribute, option_tags, strip_casein_options(options), html_options_to_use), form, obj, attribute, options).html_safe

end
```

**Comment by russellquinn** [comment]
Some manual tests I just ran:

**LEGACY STYLE with class in options**

```
<%= casein_select f, f.object, :age, [["foo",1], ["bar",2]], {casein_label: "New label", include_blank: true, class: 'hello'} %>
```

Gives:

```
<select class="form-control hello" name="article[age]" id="article_age">
    <option value=""></option>
    <option value="1">foo</option>
    <option value="2">bar</option>
</select>
```

**Passing 'multiple' in options still wouldn't work**

```
<%= casein_select f, f.object, :age, [["foo",1], ["bar",2]], {casein_label: "New label", include_blank: true, class: 'hello', multiple: true} %>
```

Gives:

```
<select class="form-control hello" name="article[age]" id="article_age">
    <option value=""></option>
    <option value="1">foo</option>
    <option value="2">bar</option>
</select>
```

**But, passing 'multiple' into the new html_options would now work**

```
<%= casein_select f, f.object, :age, [["foo",1], ["bar",2]], {casein_label: "New label", include_blank: true, class: 'hello'}, {multiple: true} %>
```

Gives:

```
<select multiple="multiple" class="form-control hello" name="article[age][]" id="article_age">
    <option value=""></option>
    <option value="1">foo</option>
    <option value="2">bar</option>
</select>
```

**And other html options could now, of course, be passed through**

```
<%= casein_select f, f.object, :age, [["foo",1], ["bar",2]], {casein_label: "New label", include_blank: true, class: 'hello'}, {multiple: true, style: "color: red;"} %>
```

Gives:

```
<select multiple="multiple" style="color: red;" class="form-control hello" name="article[age][]" id="article_age">
    <option value=""></option>
    <option value="1">foo</option>
    <option value="2">bar</option>
</select>
```

**And, this setup would even support -- and merge -- classes from both `options` and `html_options`**

```
<%= casein_select f, f.object, :age, [["foo",1], ["bar",2]], {casein_label: "New label", include_blank: true, class: 'hello'}, {multiple: true, class: 'goodbye'} %>
```

Gives:

```
<select multiple="multiple" class="form-control hello goodbye" name="article[age][]" id="article_age">
    <option value=""></option>
    <option value="1">foo</option>
    <option value="2">bar</option>
</select>
```

**Comment by russellquinn** [comment]
Fixed in Casein 5.3.0 using the proposed method above and not this PR.

**Pull request closed without merging**
